### ISSUE TITLE
can't make it

### ISSUE THREAD

**Issue by Ziggomatic** [koekeishiya/kwm#107]
OSX 10.11.2, gcc 5.3.0(homebrew)
and tried make but error. heres log.

[makelog.txt](https://github.com/koekeishiya/kwm/files/100980/makelog.txt)

**Comment by Ziggomatic** [comment]
still can't do this :cry: 

[make2.txt](https://github.com/koekeishiya/kwm/files/101127/make2.txt)

**Comment by koekeishiya** [comment]
I'll look into when I have more time.

**Comment by oleeskild** [comment]
I too had some issues when using gcc, try installing g++ instead. That fixed it for me at least.

**Comment by Ziggomatic** [comment]
>I too had some issues when using gcc, try installing g++ instead. That fixed it for me at least.  

how?

**Comment by oleeskild** [comment]
Sorry, I was mistaken. Do you have xcode installed? If not try to install that and try again.

**Comment by Ziggomatic** [comment]
yep, i've installed 7.2 and command line tools.

**Comment by koekeishiya** [comment]
> g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

Try forcing the use of the xcode g++ instead of the homebrew version.

**Comment by Ziggomatic** [comment]
1. brew uninstall gcc
2. $ make (without argument)
3. fixed thanks!
