### ISSUE TITLE
Objective-C wrapper to "improve functionality?"

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#111]
So, having access to a lot of functionality from the Cocoa framework seems like a pretty huge deal at this point, and could potentially allow for a more seamless user experience.

This requires setting up wrappers to bridge objective-c and the existing Kwm code.
There is no "ETA" for when this will happen, if at all.

**Comment by oetting** [comment]
Are you using any c++ features? Otherwise I guess it would be easier to have a "normal" objective-c program with objective-c and c code mixed. As I understand it objective-c is a superset of c. You can seamlessly drop in to c for performance critical code, for instance. 

(I know there is also objective-c++, but the objective-c/c combo is pretty common).

**Comment by koekeishiya** [comment]
It should be rather trivial to combine the Kwm code with objective-c, I just need time to get familiar with the language and the Cocoa framework.

**Comment by koekeishiya** [comment]
Gonna close this as this isn't really an issue nor enhancement at this point. I should be able to jump into objective-c whenever I come across an issue where this is necessary.
