### ISSUE TITLE
Jumping between spaces

### ISSUE THREAD

**Issue by bensinc** [koekeishiya/kwm#122]
I've noticed today that when kwm is running and I jump between spaces with my space shortcuts (Mine are cmd+number), it occasionally reverts back to the previous space, or switches to the previous space, then right back to the desired space.

I can't seem to duplicate it consistently unfortunately!

**Comment by koekeishiya** [comment]
I ran into this when experimenting a bit with the spaces and monitor code couple days ago, and I assumed I fixed it then (have not ran into them since).

I only use mission control, touchpad-gesture and ctrl+arrows to switch spaces tho, not sure if this could be specific to cmd+num (I assume this skips multiple spaces if you are on space 1 and do cmd+3, which could be what causes the issues).

**Comment by dominiklohmann** [comment]
I've been having the same issue from time to time, even when only moving from space n to space n+1. I cannot reproduce it, it seams to occur randomly. My binds are ctrl+n to switch to space n+1.

**Comment by oetting** [comment]
I see it every once in a while as well when using numbers to switch space. No way to reproduce either.

I can add that space changes happen faster (the animation) when using numbers. Even if only changing from n to n+1.

**Comment by koekeishiya** [comment]
This might be a long shot, but this could be related to updating/clearing of the focused/marked borders.
Would you mind running with borders off for some time to see if this could be the cause of the issue.

I have not come across this bug before the borders were added to Kwm.

**Comment by bensinc** [comment]
I just added "kwmc config marked-border disable" to my config file and did a reload.

It actually just did it several times while switching between my terminal space and my browser space, after disabling borders.

Let me know if that wasn't the config option you were thinking of!

**Comment by koekeishiya** [comment]
I was thinking more about `kwmc config focused-border disable`. I'll try see if I can reproduce this on my end as well.

**Comment by bensinc** [comment]
I just added that one and will let you know!

**Comment by koekeishiya** [comment]
So I managed to make this happen once, by having the cursor over the dock (which I normally have as auto-hide) and doing a normal space-transition. I also had an external monitor connected, and doing this broke the bsp-layout of both my monitors.

Something shady going on here.

**Comment by koekeishiya** [comment]
Just making another post for this. I can reproduce this problem always by doing the following steps, and I can confirm that this issue is not caused by having the borders enabled.

If i move the mouse rapidly between windows on a space, while initiating the space-transition, it will cancel the space-transition and bring the "previous" space back in focus.

**Comment by koekeishiya** [comment]
I can no longer reproduce this using my described method after the above commit. Hopefully this fixes this issue once and for all.
