### ISSUE TITLE
Allow a node to have monocle subtrees instead of a single window

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#125]
So, thinking about how to approach #114, I figured we might as well create some sort of "window rules" system. This would in theory, allow a window (not sure how to identify these yet, probably by name), to be given a set of rules, such as positioning, gaps, float, and a condition that would have to be fulfilled for these rules to be applied.

Again, I have not given too much thought regarding how this would be implemented, but I think a system similar to what I described above would allow users a lot more control regarding how applications tile, depending on their current activities. 

This would probably be something that has to be set in the config, and should not be modified during runtime.

Potential example command: `kwmc config add-rule window {some kind of syntax}`

**Comment by acarlson1029** [comment]
This feature would be a great move toward what I feel is the ultimate window manager setup.

My use case for something like this would be **stacking** new windows of the same `Owner`, while tiling new windows of different `Owners`.

Example:

- `Safari` and `iTerm` are both open, `Safari` on the Left split and `iTerm` on the Right split.

- Configure `Safari` to stack instead of tile

- Creating a new `Safari` window would overlay it on top of the existing `Safari` window (shifted down and right slightly as the default OS X behavior).
    - All `Safari` windows would be confined to this container, sized to fill with the slight shifting, but they would be stacked together.

- Opening a new application (i.e. `Slack`) would split the Left container horizontally, with the `Safari` container at the Top and `Slack` container at the Bottom.
    - The `Safari` windows would still be stacked together inside their container, resized to fit the new size.


My motivation here is to have the windows arranged based on a more productive, logical layout.

Imagine having a text editor open on one side of the screen, and a stack of PDFs on the right side of the screen. Any new PDF you open automatically drops on top of the stack of PDFs. If you want to open a terminal or browser on the screen, it tiles like you'd expect it to.

Let me know if I've piqued your interest or are having trouble visualizing what I'm talking about. I've started going through the source for this yesterday, so I'm eager to see if I can implement something like the above.

**Comment by koekeishiya** [comment]
While I agree that this is something that would be a really nice feature, there are a few challenges.

First of all, how would switching between the windows within a stacked-tile work? My first guess here is that we would need separate commands from the `kwmc window -f ..` to deal with the stacked windows, The offsetting is also gonna be tricky to achieve, so the best should would pretty much to have it work like the current Monocle mode I suppose, except it's within a tile.

Now for the implementation challenges. Kwm has been built with the following mentality at its core:  
* A tile only represents one node.
* A node can be a parent node (no window asssociated, must have 2 leaf nodes)
* A node can be a leaf node, associated with a single window
* One node contains a specific region (size) and a reference to a single window

**Comment by acarlson1029** [comment]
> First of all, how would switching between the windows within a stacked-tile work? 

OS X already handles switching between windows of the same application with `` ⌘+` `` and `⌘+~` which exists as a stop-gap, or at least a starting point.

Regarding the implementation, my feedback hits on this note:

> * One node contains a specific region (size) and a reference to a **single window**

Instead of a `Window`, we can imagine it as a `Pane` type object. Each `Pane` contains a list of 1 to N `Window`s. If there is 1 `Window`, the `Pane` behaves like the current implementation of a Window. If there are more than 1 `Window`s in a `Pane`, they stack together.

Granted, I haven't done a deep dive into the source code, so I probably don't have a strong grasp of the scope here, but I'll play around with it over the next few days to see what I can come up with.

**Comment by acarlson1029** [comment]
Thinking more about this in the context of the current codebase, what this really boils down to is creating a Monocle Subtree within a BSP.

So say the Space looks like this:

```
                    .Root.
                   /      \
                  A        M
                 / \
                B   C

┌──────────────────────┬─────────────────────┐
│                      │                     │
│                      │                     │
│          B           │                     │
│                      │                     │
│                      │                     │
├──────────────────────┤          M          │
│                      │                     │
│                      │                     │
│          C           │                     │
│                      │                     │
│                      │                     │
└──────────────────────┴─────────────────────┘
```

Although there's a bit of a communication problem that can get in the way of implementing something like this.

**Comment by koekeishiya** [comment]
> Thinking more about this in the context of the current codebase, what this really boils down to is creating a Monocle Subtree within a BSP.

Indeed this is the case. I'll start looking into this myself soon.

**Comment by koekeishiya** [comment]
I've started working on this, see branch `subtrees` for progress.
No ETA for when this will be finished.

**Comment by koekeishiya** [comment]
A node in a bsp-space is from now on referred to as a bsp-node.

A bsp-node can now be set to be treated as a monocle-subtree instead of the normal 'bsp' state.
Performing the command `kwmc tree -c monocle|bsp` will set the mode of the focused bsp-node.

If a bsp-node is in monocle mode, any new window that would normally split that node, will instead be tiled with monocle rules. To switch focus between windows that are in the monocle-subtree, the command `kwmc window -fm prev|next` must be used. 

Monocle-subtrees are currently not affected by `kwmc config cycle-focus screen`.

For the time being, if the window occupying the bsp-node is closed, the bsp-node is removed from the window-tree (standard bsp-node rules), and the monocle-subtree will become untiled.
