### ISSUE TITLE
Space Defaults

### ISSUE THREAD

**Issue by bensinc** [koekeishiya/kwm#128]
Is it possible to set defaults for a specific space? I'd like certain spaces to only float windows, for example.

I can use kwmc space -t float once it's running, but I'd like that to default a space to that from the start.

**Comment by koekeishiya** [comment]
A "proper" implementation of this is not possible due to space identifiers having arbitrary numbers from 1 to (highest I've seen personally) 3xx

This could be achieved in a tricky way, by having Kwm assign values from 0 to N in the order it detects spaces, and apply the setting that way, but I can not say how well this would work.

**Comment by dominiklohmann** [comment]
Do space identifiers change when rebooting? I've not changed the amount of spaces I have in ages.

**Comment by koekeishiya** [comment]
Pretty sure space identifiers only change when a space is destroyed / created, or a change that affects monitors happens (going to sleep, after the update to 10.11.3, and the issue mentioned #123), etc

**Comment by koekeishiya** [comment]
See `kwmc config spaces-key` and the example [init file](https://github.com/koekeishiya/kwm/blob/master/examples/init) for how to achieve this.

**Comment by koekeishiya** [comment]
This now has a proper implemenetation, see #176
