### ISSUE TITLE
Prevent tiled window from being moved / resized causes issues

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#137]
In commit affd1a2a78ddbbfdff4a09505afe7426c9c4ea5e when I actually tried to test the behavior kwm became unresponsive for a few moments, and then started to work again. 

When I tried to close the window I resized kwm became unresponsive again, and the window closed a few seconds after I issued the command to close. 

This behavior only happens when I try to resize / move a tiled window.

**Comment by koekeishiya** [comment]
Unable to reproduce on my end, weird.

**Comment by chrishoage** [comment]
I can repo it every time with Finder.

**Comment by dominiklohmann** [comment]
Can confirm this issue with Finder, but I haven't found any other Applications so far with the same issue.

**Comment by chrishoage** [comment]
Chrome will only sometimes snap back to it's original size.

Any application I move stays moved even though I have `kwmc config dragndrop disable` in my kwmrc.

It's almost like if I move a window it becomes floating.

This behavior is app independent.

**Comment by koekeishiya** [comment]
Probably has something to do with the Observer that is used to receive WindowMovedNotifciaton and WindowResizedNotification.

**Comment by dominiklohmann** [comment]
The behaviour shown in this gif[1] (which I believe is the expected behaviour) sometimes just does not work, instead I can move the window as if it was floating, but the container does not get removed.[2]

[1] 
![kwm-bug](https://cloud.githubusercontent.com/assets/4488655/12727919/81ddfb66-c91f-11e5-8b17-5854c8a1d964.gif)

[2] 
<img width="379" alt="screen shot 2016-02-01 at 20 10 46" src="https://cloud.githubusercontent.com/assets/4488655/12727984/e75311de-c91f-11e5-82e4-10ab28421c70.png">

**Comment by koekeishiya** [comment]
I can reproduce the issue you mentioned above, this is due to the observer not being updated properly. I have no idea why that is the case though. It appears to fix itself, if you focus a different window, and then switch back again.

**Comment by koekeishiya** [comment]
This change caused more issues than I would like to bother with for the time being. I've reverted the change for now. Need to figure out what causes the observer delay first.
