### ISSUE TITLE
An app opened with the `sys` command should always receive focus 

### ISSUE THREAD

**Issue by dylan-conlin** [koekeishiya/kwm#141]
When opening an app with the following command:

`kwmc bind prefix-i sys open -a /Applications/iTerm.app`

* When the app isn't opened
It opens correctly, tiles, and receives focus/border as expected.

* When the app is open already
It is activated, but doesn't receive focus/border

I think any app activated via `...sys open -a /Applications/iTerm.app` should always receive focus/border.

**Comment by koekeishiya** [comment]
This can not be done currently, because all the "sys" specifier does, is have Kwm treat it as a system command instead of interpreting it as a Kwmc command.

By system command, it literally just runs `system("open -a /Applications/iTerm.app")`
Kwm therefore has no information on whether an application was opened or activated and so on, and I doubt this is something that I will be looking into as I don't think performing an "open" command should be used for focusing.

I'd rather implement some form of window-switching, see #115
