### ISSUE TITLE
Callback events for user-created code

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#166]
With the rise of issues such as #114 and #125. 

I've decided that allowing for user-created code may be a potential approach to this problem. Now what I personally think is the most powerful solution for this, is a re-implementation of something similar to the previous live-coded hotkey system. (By doing this I will not have to actually create or import an existing scripting language and the complexity that comes with it).

I think that, by allowing the user to implement functions that are called upon certain places within the Kwm code, they will be able to impact the state of Kwm and change the behaviour by applying settings or otherwise do some actions they might want, depending on certain conditions.

A simple example of this, would be for Kwm to offer callbacks, such as `OnWindowCreate`, `OnWindowDestroy` and other relevant places. The user can then define this function in `callbacks.cpp` which can be modified during runtime. 

For the `OnWindowCreate` callback, whenever Kwm detects a new window on the screen, it would call this user written function (if defined), before proceeding with the normal routine.

The user implementation of this callback could then check how many windows are open, 
which application window was created; is  it the only window on screen; 
-> do something with screen padding.

**Comment by chrishoage** [comment]
> The user can then define this function in callbacks.cpp which can be modified during runtime.

I personally thing this is a little unreasonable. Most people (me included) will not want to write C++ code in order to achieve this functionality. 

My very personal opinion of those tickets are "out of scope" for this project. With that said I have some ideas on how to solve this problem:

Very similar to your callback idea is to register bash scripts in `kwmrc`. 

Very rough idea of what this would look like: 

`kwmc register window-create ~/.kwm/window-create.sh` 

This would pass data as arguments to this shell script, including but not limited to: window position, window name, app name. screen number, space number. 

The user can then take action depending on the arguments passed in, and the current state of kwm (though `kwmc read`.

I think shell scripts are far more approachable and compassable than writing C++.

**Comment by koekeishiya** [comment]
> Very similar to your callback idea is to register bash scripts in kwmrc. 
There are quite a few problems by doing this, firstly as you said:

> The user can then take action depending on the arguments passed in, and the current state of kwm (though kwmc read).
I would have to make assumptions not only for what kind of information every user would find interest in using as conditions, but also as to what information they would want to modify. This will quickly turn into a huge list of commands that a lot of people will probably not care about.

In addition to this, passing data as arguments would not work quite as well, as (as far as I know), bash can not interact with C structures and I'd have to pass variable by variable, instead of a single kwm_screen, window_info struct and so on.

> I think shell scripts are far more approachable and compose-able than writing C++.
I'm still curious as to why people think it is easier to delegate the work to an external language such as bash or lua for dealing with such things. e.g xmonad uses haskell.

**Comment by chrishoage** [comment]
> I'm still curious as to why people think it is easier to delegate the work to an external language such as bash or lua for dealing with such things. e.g xmonad uses haskell.

From my experience a dynamically typed language is a bit more approachable, so more people know one. It's easier for people to go from something like python to bash than python to haskell which makes the barrier to entry lower, and the ecosystem bigger.

> This is not meant for the average person tho, but rather the 5% that really wants to personalize their version without having to directly manipulate source files and maintain a fork, for something I would feel are trivial issues.

I apologize, I phrased my original post poorly. This feature can exist for those 5% who need that extra functionality, but if such a system were to exist I think it would be cool to try to make it at least partially accessible via shell scripts. I guess the biggest reason I think shell scripts should be used is from that part of the Unix Philosophy: "Write programs to handle text streams, because that is a universal interface." which I kind of agree with. 

I think some basic assumptions can be made about what is useful for shell scripts, maybe even just mirror what commands exist. It would allow for basic things like watching for a window name and pulling it to a display. Or setting a padding value when the number of windows from `kwmc read window-list` is 1. If one needs to they can jump up to the C extension. I have a hunch more people will use the callbacks if they also called out to shell scripts.

**Comment by koekeishiya** [comment]
I'm gonna close this for now. This kind of functionality will be revisited in the future.
