### ISSUE TITLE
debugging help

### ISSUE THREAD

**Issue by madmod** [koekeishiya/kwm#182]
After having windows move around seemingly at random for a while I ran kwm from the command line to get the root cause and found that it was constantly crashing and being restarted by launchctl. The following error message shows when running in iTerm. (after enabling accessibility for it)

**Edit:** I am running El Capitan 10.11.2 (15C50)

```
dyld: lazy symbol binding failed: Symbol not found: __TF10Foundationg20NSUTF8StringEncodingSu
  Referenced from: /usr/local/Cellar/kwm/1.1.2/kwm-overlay
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftFoundation.dylib

dyld: Symbol not found: __TF10Foundationg20NSUTF8StringEncodingSu
  Referenced from: /usr/local/Cellar/kwm/1.1.2/kwm-overlay
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftFoundation.dylib
```

**Comment by koekeishiya** [comment]
@chrishoage any idea?

@madmod you can prevent Kwm from trying to load kwm-overlay by making sure your kwmrc contains
```
kwmc config focused-border disable
kwmc config marked-border disable
kwmc config prefix-border disable
```

**Comment by dominiklohmann** [comment]
I played around with that a bit yesterday after thinking more about #175. Installing XCode is a temporary solution, as is putting both `libswiftFoundation.dylib` and `libswiftAppKit.dylib` in the same folder as kwm-overlay.

Ultimately this happens because kwm-overlay gets compiled with a dynamic link to `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswift{Foundation,AppKit}.dylib` (XCode dependency) instead of `/Library/Developer/CommandLineTools/usr/lib/swift/macosx/libswift{Foundation,AppKit}.dylib` (Developer Tools dependency). The latter is the default if you do not not have XCode, but only the Developer Tools installed, the former is the default if you have XCode installed.

**Comment by madmod** [comment]
@koekeishiya After adding those lines and commenting out other lines related to them that prevents the crashing.

@dominiklohmann I just installed XCode and the developer tools and rebooted but still get the same error.

**Comment by madmod** [comment]
Although I do not have a folder `/Library/Developer` for some reason.

**Comment by dominiklohmann** [comment]
Do you have the `libswiftFoundation.dylib` at the location listed in your error message?

**Comment by chrishoage** [comment]
Yeah this seems like the same issue as #175 we need some way to reference the dylibs. I won't have time to investigate a solution to this until the weekend. 

If anyone figures out a good solution in the meantime (either packaging the `dylibs` or changing the reference to not be the xcode path) feel free to change it.

**Comment by madmod** [comment]
I currently only have the Swift toolchain in that folder. Any idea how I can install the `XcodeDefault.xctoolchain`? I'm unable to find anything obvious with Google. I'll try updating XCode from the App Store.
