### ISSUE TITLE
Window tree isn't refreshed on application resize

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#183]
kwm doesn't seem to always notice when a window gets resized.
For example if I have Safari open with only one page and then open another tab the tab bar is shown and the window get resized to include the tab bar height, but kwm doesn't seem to notice this change and reposition/resize the window inside the container.

This also happens with Chrome when starting a download, with Terminal when creating a new tab etc..
Is this a limit or a bug?

**Comment by koekeishiya** [comment]
Should be fixable, I've just never come across that before. Will try to reproduce and try implement a fix I have in mind tonight.

**Comment by chrishoage** [comment]
In the meantime if you issue a `kwmc tree -c refresh` command, it will fix the window size.

**Comment by koekeishiya** [comment]
This turns out to be more complicated than I anticipated. I have solved the issue at hand, however this causes commands such as `kwmc window -t fullscreen` and similar to be resized back to its container size as well.

**Comment by koekeishiya** [comment]
> In the meantime if you issue a kwmc tree -c refresh command, it will fix the window size. 

This command will refresh the entire tree. There is a separate command `kwmc window -c refresh` that only refreshes the focused window.

I believe simply binding one or both of these commands is the appropriate solution. Forcing the window back to its container size every time `something` tries to change the window size, is bad, in my opinion.

Thus, I would say this isn't really a bug. If I do make it so that it can ignore resize notifictions caused by Kwm itself, I guess this could be a config option.

**Comment by koekeishiya** [comment]
This can be achieved by using `kwmc config lock-to-container on|off`

**Comment by cHoco** [comment]
Hey thank so much :) Haven't had the time to read the code but would it be possible to keep the window fullscreen even after a resize? Right now if a set a window to fullscreen with kwmc if the window resizes it goes back to its own container.

**Comment by koekeishiya** [comment]
Fixed in the latest commit.
