### ISSUE TITLE
Readme out of date or missing example config?

### ISSUE THREAD

**Issue by vendion** [koekeishiya/kwm#257]
In the Configuration section of the readme states that kwm will load a `$HOME/.kwm/init` file.

> In addition to the above, the file $HOME/.kwm/init is a shell script that will be ran after Kwm has finished setting up the internal configuration.
>
> A sample config file can be found within the examples directory.

but the [examples](https://github.com/koekeishiya/kwm/tree/master/examples) doesn't have a init file.  Is the init script the readme referring to the the `startup.sh` script in the directory?

**Comment by dominiklohmann** [comment]
The example init file has been as of https://github.com/koekeishiya/kwm/commit/ea3a884ca7b09942f4e44bc8e0688837eb84d2e0.

**Comment by koekeishiya** [comment]
The example init is obsolete, due to better ways to hande that particular case it was used for. 

The init file is just a shellscript, that will be ran by Kwm automatically, if it exists. I personally have no need for it anymore, but figured there was no need to remove the support in case others may want it.
I also have no clue what kind of tasks people would like to automate, so an "example" init is not in any way helpful.
