### ISSUE TITLE
drag-and-drop feature

### ISSUE THREAD

**Issue by atsepkov** [koekeishiya/kwm#28]
Very interested in the evolution of this project, I use Hammerspoon at the moment, but would love to switch once the experience more closely resembles that of `awesome wm`, which I use on Linux. I do have a question.

From the README:

> The other option is to make the window floating and manually move it with the mouse, then un-float it.
> Moving a window directly with the mouse WILL BREAK the window-trees of both monitors.

Why not check if the window is already in floating state when mouse dragging is initiated and switch to floating state automatically if it isn't to prevent tree breakage? Is it a technical limitation, conflict with another feature or just hasn't been done yet?

**Comment by koekeishiya** [comment]
Haven't looked into it too much, however I'm pretty sure there is a technical limitation. The moment the user initiates mouse dragging, the mouse move event that I track using event taps no longer gets called.

**Comment by koekeishiya** [comment]
I did some testing and if the window is simply dragged to another monitor, the window tree of the monitor that the window was previously on, will be incorrect - the new monitor tiles as expected.

However, what you can do is move the window on the current screen to make it floating, instead of using a hotkey.
