### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#342]
If anyone for some reason want to create some sort of a beginners guide, or more detailed explanations of the features Kwm provides, the wiki is open for everyone to edit.

I'm mentioning this as I will keep doing very brief information in the `kwmc/README.md` which probably may not be detailed enough for anyone that is unfamiliar with the concepts from other tiling window managers.

I don't expect anyone to do anything like this, but figured I'd mention it anyway.

**Comment by neon64** [comment]
I perhaps might be able to help. Over the past few weeks I have gone from noob to sort-of-alright at kwm.

The first thing that annoys me is the readability of the [kwmc docs](https://github.com/koekeishiya/kwm/blob/master/kwmc/README.md) and also how they are buried deep inside the source tree. I converted those docs to HTML and made it look a bit prettier. You can see the results [here](http://neon64.github.io/kwm/kwmc.html). The issue is, I realised you use Merlot to generate the site so opening a pull request directly to the gh-pages branch might be futile as it would just get overwritten by the generated files.

I suppose I'm just commenting here to ask if you think that page is worth adding to the website.

**Comment by koekeishiya** [comment]
This looks like a great improvement indeed. The only reason that I am using the predefined themes, is that I have not yet had the time to write a somewhat good looking theme myself.

I noticed that you did also make changes to the `kwmc/README.md` as well. 
Please do submit a PR for that if you'd like.

**Comment by neon64** [comment]
Thanks for the support. So just clarifying, you want `kwmc/README.md` completely removed in favor of the docs on the website? I'll open a pull request as soon as I've got time

**Comment by matthewdias** [comment]
Would probably be a good idea to link to the docs on the website from the main README in that case.

**Comment by koekeishiya** [comment]
The main readme will just feature a very very brief description, an image, and a link to the website. 

I will also most likely get rid of the kwmc man file, as I personally do not want to maintain 3 different sources of information.
