### ISSUE TITLE
Send window to next space / desktop

### ISSUE THREAD

**Issue by SxDx** [koekeishiya/kwm#37]
Seems like there is currently no way to send windows to  other spaces.
Do you have any plans to implement this? (Similar to sending windows to other screens)

**Comment by koekeishiya** [comment]
This might be tricky to implement properly without feeling sluggish.

What I usually do if i have to send a window to a different space, is make it floating, open mission control and drag it to the space i want, select my new insertion point and un-float it.

I realize this sounds kinda tedious, however if a try at making something like this automatic, in the end you would not be able to pre-select the insertion point, and would most of the times have to remove it from the tree and insert it where you wanted it originally.

I'll keep it in mind in case I'm able to come up with a solution that could work.

**Comment by koekeishiya** [comment]
I've thought about this quite a bit and this is not something that I wish to try to implement, due to OSX restrictions. See the comment I made above for how you can still move windows to other spaces in the rare cases that this is needed.

Note: I say rare cases as Kwm is meant to be used with "dedicated spaces", by which I mean that every space should have a specific role such as development, procrastination and so on and I would assume that a window should not be moved to spaces regularly, but rather be opened on that space by the user.
