### ISSUE TITLE
Kwm and iBooks?

### ISSUE THREAD

**Issue by colonelk1** [koekeishiya/kwm#389]
Hey --- I've tried following the instructions for issue #40, in an attempt to get Kwm and iBooks working, but nothing seems to work. I have the following in my .kwm file --- trying to cover all bases.

kwmc config add-role AXStandardWindow iBooks.app
kwmc config add-role AXStandardWindow iBooks

kwmc config add-role AXTextField iBooks.app
kwmc config add-role AXTextField iBooks

Thanks for kwm, btw --- it's an awesome window manager.

**Comment by koekeishiya** [comment]
I have never used iBooks, so not completely sure. The main window of iBooks seems to work just fine for me with no custom rules though?.

**Comment by colonelk1** [comment]
Interesting --- I even redownloaded kwm from home-brew and not a single iBooks window is registered by it.

**Comment by koekeishiya** [comment]
Version 3.0.0 was just released on homebrew.
Try uninstalling your current version of kwm and download the new version.

```
brew uninstall kwm
brew update
brew install kwm
```

If you have changed a lot of the default config, you need to update it to the new syntax for version 3.0.0.
If you are running the default config, simply copy the new default config provided with the latest homebrew release.

**Comment by nino** [comment]
The problem is with opening books in iBooks. When you double-click on one, it displays an animation (which seems to be an `AXUnknown`), and then opens the actual book as an `AXStandardWindow`. This window, however, doesn't get recognized and after the opening animation, the tiling layout on all spaces gets reset.

Even adding `kwmc rule owner="iBooks" properties={float="true"}` to the config file doesn't work. The command does make the library window float, but opening books still messes up the layout. Is it possible that the opening animation doesn't get reported as being from the iBooks app but rather something else, so that the `float="true"` thing gets ignored for the animation?

(I'm on kwm 3.0.1, from homebrew)

**Comment by koekeishiya** [comment]
> This window, however, doesn't get recognized and after the opening animation, the tiling layout on all spaces gets reset.

Sounds like Kwm just crashed when the window spawned.

**Comment by nino** [comment]
The crash seems to no longer happen in version 3.0.5. The iBooks app still doesn't tile correctly (the window flies off the screen), but when iBooks is set to float, it seems to be working.

**Comment by koekeishiya** [comment]
As the crash seems to be gone, I'm gonna accept the float as a solution to this problem.
