### ISSUE TITLE
Closing a window breaks selecting previous or next window

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#41]
It might be something with GetNodeFromWindowID returning NULL if the current window has disappeared. 

The same happens if I minimize a window.

**Comment by koekeishiya** [comment]
Is this on a space using bsp or monocle mode?

**Comment by oetting** [comment]
It happens with both. If I open a new space and open three terminal windows (command-n three times with with terminal in focus) and then close one window (command-w), I cannot move to the next or previous window. 
I can "fix" the problem by creating another new window.

**Comment by koekeishiya** [comment]
Just tried this and I cannot reproduce. Focus switches just fine for me.
I created a new space, opened a new iterm, created 3 additional windows using cmd-n, closed one of the windows using cmd-w, and I can still switch focus between the remaining windows.

**Comment by oetting** [comment]
Ok. I think I figured it out. I had the menubar visible and did not disable menu-fix. So focus did not follow mouse. With that corrected it now works. The window below the cursor is focused when I close another window. 

If I place my cursor so that no window is below it I can still make it break. Can you reproduce that case? If so, maybe it should default to focusing the first window in the space, if no other window can be found (or maybe the one focused before the one that was closed, but that of course requires tracking a window history).

If I disable focus, the windows do get "kwm focus". Even if I close the currently focused window. But the windows do not get "osx focus" so I cannot send input to them.

**Comment by koekeishiya** [comment]
So I've been able to reproduce the first case where the mouse is not above another window when performing the close, the focus will break, however Kwm does not segfault or anything. I simply have to use the mouse to re-focus. Is this the same for you?

Basically that is the purpose of disabling focus, if you do `kwmc config focus disable` no focus changes should occur at all.

Regarding the first issue, that is something I should be able to do relatively easily.

**Comment by oetting** [comment]
Yes, the first case is the same for me. It is not really a problem when you have focus follows mouse, but it might be better to have it focuse "something".

I do not really like to have focus follow the mouse. What I would prefer is a mode that allows me to focus windows using the keyboard, and using mouse clicks.. This is almost what I have with focus autoraise, and menubar visible, because the menubar disables mouse-focus, and the autoraise value allows me to focus windows using the keyboard. But because nothing is focused when I close windows, it breaks in that case, and focus with mouse clicks does not work either.

**Comment by koekeishiya** [comment]
Aight, I agree all of that seems very useful at this point in time.
It has just slipped my mind since the original project was only to achieve focus follows mouse, and so that part of the code is 2-3months old.

I can and probably will add another mode as you suggested, I can see that being nice to have.
About Kwm not updating focus on mouse-clicks is simply an oversight on my part due to reasons mentioned earlier.

**Comment by oetting** [comment]
That sounds good. Awesome project, just as I was ready to give up on OSX because of the window manager, then you came along :)

In the mean time, maybe I should give focus-follows-mouse another shot. 

Close at will, if you do not wan't to use this issue for the click focus thing.

**Comment by koekeishiya** [comment]
I'll just leave this issue open until I have actually pushed a commit.
I've made it so that `kwmc config focus disabled` allows for the functionality that you described, instead of creating a separate mode. There is no reason why keyboard focus should not work at all times, and if people do not want this, they can simply remove the hotkeys provided in the config.

I still have to work out how I want to handle the focus when a window is closed.
Will probably push the commit later tonight.

**Comment by oetting** [comment]
Sounds good. Thanks again.

**Comment by koekeishiya** [comment]
When a window closes, the "root" container will get focused, in most layout this is the leftmost-window on your screen. I may look into adding focus-history later so that "focus window that previously had focus" which seems more useful.

Left-clicking on a window will now make Kwm see it as focused.
Moving focus with keyboard using `kwmc config focus disabled` will properly perform the raise action so input is received properly.

Thanks.

**Comment by koekeishiya** [comment]
I forgot to do the above change for monocle mode, and just pushed a commit that fixes this issue completely.
