### ISSUE TITLE
Code Documentation?

### ISSUE THREAD

**Issue by z3t0** [koekeishiya/kwm#531]
I apologize if I am being naive, but I would really like to contribute to this project and the first thing I noticed was a lack of code documentation. Is this something that is not wanted or just something that has not been considered since there are more important things to do? I just thought having documentation would make this project more accessible to less confident developers.

Thoughts? Comments? Criticisms?

**Comment by choco** [comment]
If you mean proper development documentation, yes it's missing, but the code is pretty straight forward and there are usually inline comments when things get hairy.
Don't think it was a conscious choice but there are surely more pressing issues, one above all is good documentation for new coming users, some functionality isn't even described anywhere so that's the next step we gotta work on.

**Comment by koekeishiya** [comment]
> Is this something that is not wanted or just something that has not been considered since there are more important things to do?

Uh, well, it just kinda turned out this way. Back when I started development on Kwm, it was supposed to be a very small personal project, so I didn't care about commenting as everything was very straigthforward. I never imagined it would turn into what it is today, despite all the current problems.

I remember most of the decisions that I made, why they were made and so on, personally, so if people would like to contribute, I can add documentation over time.

I am really busy for the time being, so this will not be happening for quite some time.

Some general information about the structure:

The `axlib` directory contains code that interacts with the MacOS APIs, and is supposed to expose these in a more friendly manner (although it has its problems still). The code here is pretty straightforward, and it also has a reasonable amount of comments describing edge-cases and so on.
This would probably be the goto for getting into the codebase.

The `kwm` directory contains code that uses the `axlib` library and is basically the window manager itself.

**Comment by z3t0** [comment]
Thanks for the answers! One more question, why choose c++ as more mac devs seem to stick with Obc / Swift. Don't get me wrong C is my favorite, and c++ next of course. I'm only curious

**Comment by koekeishiya** [comment]
> One more question, why choose c++ as more mac devs seem to stick with Obc / Swift. 

I personally think Obj-C is the worst language ever, so yeah.

I have not really had the time to look into Swift, so i can't really say anything about that. It might be worth looking into in the future / for future projects.

**Comment by koekeishiya** [comment]
I've more or less shifted work to a new WM because of architectural differences between what I would like, and how Kwm is currently built.

> but I would really like to contribute to this project

It is very early in development still as I'm working out the architecture and experimenting a bit.
Ideas  / suggestions are welcome. 

https://github.com/koekeishiya/chunkwm
