### ISSUE TITLE
Recurring window issues

### ISSUE THREAD

**Issue by Speaky10k** [koekeishiya/kwm#54]
This is an update on the issues I'm facing beginning documentation in #36.  I would not be surprised to find out that there is something wrong with my personal setup that is causing this issue.  It is highly unlikely it's related to secure keyboard entry.  KWM will stop detecting any new windows from any application, discontinue following the mouse, and since the last update KWM will no longer interact with any windows after the mystery problem begins presenting that session.  iTerm doesn't need to be an active window or even an open application, it can occur across Outlook, Mail, Firefox, Safari, Chrome, and Evernote in my experience, I'd venture to guess it can occur in any application.  It can occur without meta keys being pressed or anything calling KWM--it occurred while trying typing this up where the only meta key I've pressed is shift to create caps and the pound sign in the first sentence.

For testing purposes, I enabled focus-follows-mouse to help diagnose this, and it ended up helping because it removed a lot of the variables as to what could be causing this--as soon as the focus stops following my cursor, I know that the mystery problem has occurred.  KWMC doesn't notice any issues in these circumstances, it just thinks that whatever window was in focus at the time is perpetually focused

I'm starting to think continued testing will require a fresh OS install, but I'm uncertain of whether or not I'll be able to find the time to do this soon so I thought that giving the information I have gathered would be better than sitting on it.

**Comment by chrishoage** [comment]
I have found that sometimes `kwm` appears to crash, or have crash like symptoms. For me `killall kwm` fixes the issue because `launchd` restarts it as soon as the process exists. 

I still don't have 100% reproducible steps yet. Once I find solid STR I was planning on opening a ticket. But I am also experiencing this issue sometimes.

**Comment by koekeishiya** [comment]
Could you reproduce it with debug prints enabled and just pipe them to a file that you can post here or send to me?

The debug prints aren't accurate by any means, but it could give me a start as to which part of the system may be faulty. I have yet to run into any of this at all, however after reading this there appears to be a bug in the window detection or tiling system.

Could you also try to see if you can reproduce the above with tiling disabled, but focus-follows-mouse enabled?

Thanks, I'll try go through the code for this as well and see if I can see something that looks awkward.

**Comment by koekeishiya** [comment]
" and since the last update KWM will no longer interact with any windows after the mystery problem begins presenting that session."

This caught my attention, I did make changes lately in a certain part of the tiling logic. You wouldn't possibly remember which commit you were on before updating to the latest one?

**Comment by Speaky10k** [comment]
I do not, sadly, know what specific commit I was on.  I can tell you it was retrieved on Jan 2nd, if that's helpful at all.

**Comment by herrbischoff** [comment]
I have the exact same issue. `kwm` appears to crash randomly. However, based on observation alone, I'd suspect moving the mouse cursor from one one monitor to the other (I have a 2 monitor setup) *sometimes* makes `kwm` lose its ability to `focus-follows-mouse`. `killall kwm` *sometimes* helps but recently it does not anymore. After a reboot, everything works again as expected.

Can I do something to help you diagnose the issue?

**Comment by koekeishiya** [comment]
@herrbischoff This issue I do know what is causing, and is happening because of the current implementation of multiple-monitor support (this approach will probably be re-written from scratch when I get back home later in january and have monitors to test with).

I have no idea what causes Kwm to crash while not using external monitors tho, as was mentioned in #36

**Comment by herrbischoff** [comment]
Good to know, thanks. So, for the time being, there's no workaround, right? Having duplicated the setup from the screenshots, I have grown to rather love it and wouldn't want to reboot all the time. ;)

**Comment by koekeishiya** [comment]
The bug you described is happening because of how the space/monitor code currently works.
I use an API called CGSGetActiveSpace, however this does not update the space-id when moving to mouse to a new monitor, it only changes when the user actually performs a mouse-click on the monitor.

I have currently implemented a very poor system that basically just does:
while(Previous space == Current Space)
    // Call CGSGetActiveSpace
   // sleep some, wait for system API to refresh?

Now what I assume is happening is that Kwm gets stuck in this loop and it appears to the user as if it has crashed.

**Comment by herrbischoff** [comment]
I see. The active window is also not being reported correctly via `kwmc focused` it stays stuck on the last window open before the crash/loop.

**Comment by koekeishiya** [comment]
@herrbischoff I have changed how transition between monitors occur in the latest commit and the issue you've been having should now be fixed. There may have been new (smaller) bugs introduced by this, please do let me know if you encounter some

@Speaky10k The changes in the latest commit may have solved your issues as well

**Comment by Speaky10k** [comment]
It has definitely improved; I haven't had a single instance where I needed to kill kwm for continued function.  Previously, it wouldn't be at a regular interval but it always happened after leaving my computer idle for the night, and it did not over the previous evening.  Seems fixed to me.

Off topic, I was trying this as a lark while I was frustrated with my hammerspoon config, thinking "well the OS X tiling WMs are all bad enough it'll renew my appreciation for this implementation."  Now I'm quite happy as to how wrong I was.  Thanks!

**Comment by koekeishiya** [comment]
Glad to hear that. I'll leave this issue open, feel free to close it when you believe that things has been fixed completely.

**Comment by Speaky10k** [comment]
I'll close it now, then, as I only left it open in case you wanted it so.

**Comment by herrbischoff** [comment]
@koekeishiya: I have compiled the latest master and will test it extensively. So far it looks good.
