### ISSUE TITLE
[4.0.3] Change space of a specific display

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#562]
Hi,

I use a multi displays setup and would love to have the ability to map a keyboard shortcut to change the space of a specific screen.

I tried to setup khd with the following config, but it looks like it doesn't work:

     cmd + alt - 0x0a         :    kwmc display -f 0 && kwmc space -fExperimental 1

How can I achieve this?

Thanks

**Comment by koekeishiya** [comment]
The following works for me
```
cmd + alt - 0x0a      :   kwmc display -f 0; sleep 0.1; kwmc space -fExperimental 1
```

**Comment by dominiklohmann** [comment]
If you're running macOS Sierra, instead of `kwmc space -fExperimental 1` you can enable Reduced Motion in the Display Accessibility settings and just use a normal space transition (e.g. `khd -p "ctrl - 1"`, which then is a simple fade animation running quite quickly. This works well since the normal space transitions work across displays, so you can even change the space on an inactive display.

<img width="780" alt="screen shot 2017-01-17 at 13 51 53" src="https://cloud.githubusercontent.com/assets/4488655/22021242/5955c8b6-dcbc-11e6-84ac-d047ad4b60f2.png">

**Comment by mickaelperrin** [comment]
@dominiklohmann great to know ! `fExperimental` is awesome but has lot of drawbacks sadly. Finally, a good point to upgrade :) BTW, how do you use the standard transition with kwm ? The [documentation](https://koekeishiya.github.io/kwm/kwmc.html#spaces) only shows how to use the `fExperimental` option.

@koekeishiya Yeah, adding the sleep does the trick !

**Comment by dominiklohmann** [comment]
> BTW, how do you use the standard transition with kwm?

You can set the shortcut for that in the system settings. You can set shortcuts for up to 20 spaces (iirc), if that is how many you have when you open the system settings. If you have 2 spaces on your main display and 2 on your second display, pressing `ctrl - 1` would switch to the first space on the first display and `ctrl - 3` would switch to the first space on the second display (assuming default keybindings).

If you want to use these in other Khd commands, just do `khd -p "ctrl - 1"` to emulate a keypress.

<img width="780" alt="screen shot 2017-01-17 at 17 46 46" src="https://cloud.githubusercontent.com/assets/4488655/22030212/36d06082-dcdd-11e6-975b-be4468665b3f.png">

**Comment by mickaelperrin** [comment]
@dominiklohmann awesome, thanks a lot !
