### ISSUE TITLE
[4.0.5] Equal sized windows

### ISSUE THREAD

**Issue by maletor** [koekeishiya/kwm#600]
How do I make it so that new windows are equally sized instead of where the focused window is again split in half?

For example, I want:

|---|---|---|
|---|---|---|
|---|---|---|

not:

|---|-|-|
|---|-|-|
|---|-|-|

**Comment by maletor** [comment]
Found https://github.com/koekeishiya/kwm/issues/576.

Bummer

**Comment by koekeishiya** [comment]
You can achieve this by editing away the focused window lookup part. This is the default behaviour if no focus is available, but is not a config setting

**Comment by koekeishiya** [comment]
Actually nvm, misunderstood your post at first.

**Comment by dominiklohmann** [comment]
What if there was a command that worked similar to `C-w =` in vim, which equalizes all split sizes (horizontally and vertically)? Sounds like a good solution to me.

**Comment by koekeishiya** [comment]
> What if there was a command that worked similar to C-w = in vim, which equalizes all split sizes (horizontally and vertically)? Sounds like a good solution to me.

Will experiment with different behaviours. It would be nice to be able to select to only equalize certain parts of the window-tree, and not ALL of it.

Need to figure out some intuitive way to deal with selectors.

Most likely will not happen in **kwm**(if it does, it will probably be a simple one that just equalizes the entire tree). For **chunkwm** I want to do it a bit more sophisticated.

**Comment by maletor** [comment]
@koekeishiya, for reference:

https://i3wm.org/docs/userguide.html#_tree

**Comment by chrishoage** [comment]
It's interesting to me how people come to a Binary Space Partitioning window manager asking it to behave like i3, which has a much simpler tiling methodology. 

What is being asked for here is not BSP partitioning with fibonacci tiling, which is what kwm is. 

With that said

> Will experiment with different behaviours. It would be nice to be able to select to only equalize certain parts of the window-tree, and not ALL of it.
> Need to figure out some intuitive way to deal with selectors.

What BSPWM does is kind of interesting. It allows you to enter a mode which places an overlay over the current container to prepare a split. This allows you to visualize where the split would be. 

There could be an extension of the border system that places a translucent overlay over the tiles that could be changed to include more or less of the tiles, and this could act as a selector of tiles. 

This is different that BSPWM of course as BSPWM only allows you to use the overlay to prepare the next split, not select multiple containers/tiles.

**Comment by koekeishiya** [comment]
> Really, we just need a way/concept of containers and the rest will flow from there.

This is already a thing inside the codebase, its just coming up with some syntax that is intuitive from the user perspective, but at the same time should be relatively easy for me to parse in code.

I have a proof of concept working already, but it only takes the x-axis into account when performing the equalize. It sort of works like the behaviour vim offers, as @dominiklohmann  mentioned.

> As an aside, how does this relate to the new project happening in another repository?

I've more or less stopped developing **kwm** due to core issues that are hard to fix, and are the causes of a lot of the instability that you probably have noticed while using it.
The reasons for these are just bad architectural decisions that I've made when the development started, due to lack of understanding and properly handling a lot of issues that arise when dealing with lower level MacOS APIs.

Because of the above, I recently started a new project from scratch that will essentially be a higher-quality software version of **kwm**. There may be some feature dispartiy, but I'm very much trying to replicate the features from **kwm** that I think have been a succcess. I'm very satisfied with the result so far, though progress has stagnated lately due to work. 

The project is very usable at the moment for single-monitor setups, but still lacks some features that **kwm** does provide.

If you're interested: [repo](https://github.com/koekeishiya/chunkwm)

**Comment by koekeishiya** [comment]
Implemented on master.

command: `kwmc tree equalize root`

**Comment by koekeishiya** [comment]
**NOTE**:

The implementation in **kwm** is working, but only considers the vertical axis when performing its calculations, and is thus not a complete version.

The version implemented in **chunkwm** is a complete version and equalizes both the vertical and horizontal axis as appropriate.
