### ISSUE TITLE
Changing screen focus will sometimes result in null focus

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#61]
Occasionally moving focus between screens using `screen -f prev | next` will cause no window to be focused at all. `window -f prev | next` then does nothing. Using `screen -f prev | next` will "fix" the issue and focus a window again.

**Comment by koekeishiya** [comment]
This turned out to be rather tricky to implement.
In the latest commit, this is what happens for me:
I do `screen -f prev|next|id` and the new monitor gets focus,
the first leaf node gets Kwm focus however OSX does not focus it.

This makes it possible for the user to restore focus with `window -f prev|next`.
This same issue exists for `window -f prev|next` if focus cycled to a different screen.
