### ISSUE TITLE
Follow focus as a seperat app

### ISSUE THREAD

**Issue by kirkegaard** [koekeishiya/kwm#617]
I was wondering if it would be possible to take the part of kwm that enables mouse follow focus in its own app or daemon or is it tied into kwm really deep? I havent looked that deep into the code but its something that i've never figured out how to do and always wanted to have. Sorry this is kind of unrelated and in a deprecated project

**Comment by dominiklohmann** [comment]
Check out https://github.com/koekeishiya/chunkwm. Also note that Kwm is deprecated with chunkwm being its replacement.

chunkwm is based on a plugin architecture and since focus follows mouse is a separate plugin for it, you might choose to only load the focus follows mouse plugin (`ffm.so`).

Your chunkwm config file would be just this:
```
chunkc core::plugin_dir /path/to/plugins
chunkc core::load ffm.so
```

**Comment by kirkegaard** [comment]
Oooh yeah that would totally be a way to do this. Thank you! :)
