### ISSUE TITLE
Configure which features the user wants enabled

### ISSUE THREAD

**Issue by teoljungberg** [koekeishiya/kwm#7]
I've been searching for a good focus-follows-mouse utility for a long while, and `kwm` handled that just perfectly! Thank you.
All though, there are features of `kwm` that does not fit into my current workflow.

Would it be reasonable to configure `kwm`, either during the compilation stage, or in the `.kwmrc` file, to enable/disable the different features the user wants?

**Comment by kosikfll** [comment]
Well that's going to change I never gave permission for any of this and now I want to do organization and I'm going to be learning and working with it and I have a license  a  Property license .  Something they should've checked before they try to steal it .

**Comment by koekeishiya** [comment]
Currently no plans to allow for separation of functionality, althought it should be quite possible to do. Will look into it in the future.

**Comment by kosikfll** [comment]
Is that because you guys betrayed me I rent the application information you call me dumb dumb dumb dumb dumb I have a brain injury I'm disabled. That is so messed up that what you guys did please refund my money back. And I need to know why you betrayed me and what you plan on doing this is my application isn't it. I will disable it then if you guys are going to betray me like this.

Sent from my iPhone

On Dec 22, 2015, at 4:51 AM, koekeishiya <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently no plans to allow for separation of functionality, althought it should be quite possible to do. Will look into it in the future.

-

**Comment by koekeishiya** [comment]
You can now chose to only use  the focus-follows-mouse by disabling Kwms tiling and hotkey functionality using the `$HOME/.kwmrc` file.  Specifically adding `kwmc config tiling disable` will disable tiling.

**Comment by teoljungberg** [comment]
After running this for a week or so, this is working out great. Thank you.
