### ISSUE TITLE
Non-resizable windows can not be "unfloated"

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#84]
Non-resizable windows are now autmatically floated (it works great for the suggestion list when composing mail, thanks). This causes issues in some cases where I would like to either have the window in bsp or monocle mode. It would be great if I could unfloat an automatically floated window. 

I have hit this issue with the android emulator and the system preferences dialog.

**Comment by koekeishiya** [comment]
This would require storing yet another list of floating windows that should be ignored from being permanent floating and so on.

My initial thoughts behind the `config float-non-resizable` was really just to avoid having to specify them all manually with the `config float application` option. Personally I prefer things like the system preferences dialog to not be tiled, as it breaks (in most cases) the layout due to not being resizable.

You could potentially look into using autofocus instead of autoraise in these cases.

**Comment by oetting** [comment]
It could be a flag in the window struct indicating that it was un-floated by the user, and then checking this flag when considering the autofloat.

But I can see how this entire autofloat thing might bring more problems than it is worth.

**Comment by koekeishiya** [comment]
I realize I never really replied to this issue, sorry about that.

> It could be a flag in the window struct indicating that it was un-floated by the user, and then checking this flag when considering the autofloat.

The reason I cannot simply do this, is that the window_info struct is just a cache really that is flushed/refreshed multiple times per second (this is the way Kwm is designed to detect change in visible windows). 

This probably sounds like a bad solution, but it allowed for what I consider to be the most precise method to detect new windows or windows that have been closed.

**Comment by chrishoage** [comment]
> flushed/refreshed multiple times per second

Ah, this might explain the rise in idle CPU usage. Before kwm has a very minimal impact on cpu resources, now it is always at ~20% usage when idle. 

I haven't seen any huge downsides to this, just pointing out that kwm does now use more CPU resources. It's RAM usage is very minimal. < 50MB for the overlays and the daemon.

**Comment by koekeishiya** [comment]
> Ah, this might explain the rise in idle CPU usage. Before kwm has a very minimal impact on cpu resources, now it is always at ~20% usage when idle. 

Really 20%? Holy ****, it's idling at less than 3% for me. I'll revert the change back to how it was previously. Although that will cause it to be "less snappy".

**Comment by chrishoage** [comment]
<img width="562" alt="screen shot 2016-02-15 at 11 06 17 am" src="https://cloud.githubusercontent.com/assets/1056886/13057919/2d7d447c-d3d4-11e5-815a-add480e80712.png">

Not sure what I'm doing wrong. I'll try a restart. If you say it's at 3% for you it maybe something up with my system / setup.

**Comment by koekeishiya** [comment]
Actually it's idling at around 6-7% now, but still. 20% seems way over the top. I'll look into using an actual timing system instead of relying on usleep as it can behave differently across machines.

**Comment by dominiklohmann** [comment]
Currently idling at 13% for me, fully maxed out 2012 rMBP. It's about even with the WindowServer process in terms of CPU usage, but has by far the most Idle Wake Ups from any process running.

<img width="516" alt="screen shot 2016-02-15 at 20 08 24" src="https://cloud.githubusercontent.com/assets/4488655/13057970/01f87bfe-d420-11e5-8014-d44e985b016a.png">

**Comment by koekeishiya** [comment]
I've reverted it back to the value used previously. Currently idling at 0.5% cpu usage for me now.

**Comment by chrishoage** [comment]
With that last update I'm down to 1.5% idle, which is right around where I was before. Idle Wake Ups are down to 9.

**Comment by dominiklohmann** [comment]
Maybe this can be a configuration settings? What drawbacks come with the lower flush rate?

**Comment by koekeishiya** [comment]
It's basically setting the interval of how often Kwm should look for changes in visible windows on the screen.

**Comment by chrishoage** [comment]
Are there window events that can be subscribed to? Or are these not reliable? Being notified of window changes (if such notifications are available) seem better than polling for updates? 

Maybe these notifications are only available in Obj-C APIs...

**Comment by koekeishiya** [comment]
There are notifications for them, but you would have to first find all applications open. Then subscribe to all of these applications. They are only available in Obj-C (this is not a problem) but I find the notifications to not be reliable enough, which is why (from my limited use) Amethyst does not feel as smooth in this regard, in my opinion.

**Comment by dominiklohmann** [comment]
> The lower the interval, the faster it will detect changes in open windows, and it will feel more "responsive" to the user

If there is no other way than frequent polling to solve this problem, I would like to suggest making this a value that can be set using `kwmc config`.

> which is why (from my limited use) Amethyst does not feel as smooth in this regard, in my opinion.

Sacrificing smoothness is not a viable option, I think.

Does kwm use some kind of busy waiting anywhere else? What are the exact drawbacks of the notifications and in what way are they unreliable?

**Comment by chrishoage** [comment]
Throwing ideas against the wall: I wonder if there is a middle ground,
using the notifications to know when to request the window list again?

Maybe this could be used in conjunction with polling? No idea if my idea is
a good one.

I personally would like to see a universal solution, with a config option
for the polling frequency as a last ditch effort.

**Comment by koekeishiya** [comment]
> Does kwm use some kind of busy waiting anywhere else? What are the exact drawbacks of the notifications and in what way are they unreliable?

There is no form for polling or waiting in the other parts of Kwm.

From my experiences, the notifications do not always get reported as they should, which would cause the expected behaviour to not take effect. An example of this actually already in effect in Kwm with the observer that tracks changes made to the currently focused window.

> Throwing ideas against the wall: I wonder if there is a middle ground, using the notifications to know when to request the window list again?

This would again have the same drawbacks as just using pure notifications, as they would still be the initial step to request the window list.

Relevant notifications:
https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWorkspace_Class/#//apple_ref/c/data/NSWorkspaceDidLaunchApplicationNotification

https://developer.apple.com/library/mac/documentation/ApplicationServices/Reference/AXNotificationConstants_header_reference/#//apple_ref/doc/constant_group/Miscellaneous_Defines

**Comment by koekeishiya** [comment]
Decided that I'm not gonna be implementing this.
