### ISSUE TITLE
marked-border stays on screen after moving to new display

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#90]
Steps to reproduce: 

1. `window -t mark` a window
2. `screen -m 1` marked window

Actual Result: Marked border remains where marked window was. 

Expected Result: Marked border is cleared when marked window moves.

**Comment by koekeishiya** [comment]
This behaviour probably happens if you mark a window and do `window -s prev|next` as well?

The fix is to just have Kwm call the UpdateBorder function to clear the border everytime the marked window is moved.

**Comment by koekeishiya** [comment]
Would you want to have the border and marked window to be cleared, or updated to be set to the new screen?

**Comment by chrishoage** [comment]
I think having the marked window be cleared would be in line with some of the other behavior i've seen, but I'll leave that up to you. 

I would also like the ability to toggle a marked window back off again. Before when there was no border it wasn't a big deal, but now not having the ability to "unmark" something is ever so slightly annoying. 

I imagine "marking" a marked window would "unmark" it. 

Moving a "marked" window to a new display would clear any mark it had? That behavior is up to you though, what ever you think makes the most sense.

**Comment by koekeishiya** [comment]
Just simply giving focus to a different screen already clears the marked window. I don't remember exactly why I did this, but there must have been a reason for it.
I think it's best to keep this behaviour consistent because of that.

Issuing the mark window command, on a marked window will now unmark it.
Just doing some more testing before I push the changes.
